handle *exec.ExitError a bit better
For example, when pressing "ESC" to cancel picking an emoji, before:

    $ wofimoji; echo $?
    error: exit status 1
    1

versus after:

    $ wofimoji; echo $?
    1

With this change, if wofi prints a useful error to stderr,
we will also print that instead of just "exit status N".